server:
  port: 9527
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID #防止Cookie冲突，冲突会导致登录验证不通过
oauth2-server-url: http://localhost:8083
spring:
  application:
    name: oauth2-client
security:
  oauth2:
    client:
      client-id: client-a
      client-secret: client-a-secret
      access-token-uri: http://localhost:8088/oauth/token
      user-authorization-uri: http://localhost:8088/oauth/authorize
      scope: read,write
      pre-established-redirect-uri: http://localhost:8080/session
#      此处特别重要一定要配置，否则不会生效，配置了自定义的回调地址就必须将默认的回调禁止，原因不做过多说明。
      use-current-uri: false
    resource:
      user-info-uri: http://localhost:8088/user
      prefer-token-info: false